In [1]:
from constants import *
from basic_model import BasicModel
from preprocessing_helper import *
from submission_helper import *
from keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, TensorBoard

import os
import sys


Using TensorFlow backend.


In [2]:
# Load a set of images
root_dir = "../dataset/training/"

image_dir = root_dir + "images/"
files = os.listdir(image_dir)
n = len(files)
print("Loading " + str(n) + " images")
imgs = [load_image(image_dir + files[i]) for i in range(n)]
print(imgs[0][2])

gt_dir = root_dir + "groundtruth/"
print("Loading " + str(n) + " images")
gt_imgs = [load_image(gt_dir + files[i]) for i in range(n)]
print(files[0])

X_train = imgs
Y_train = gt_imgs

TRAINING_SIZE = 10 

data_dir = '../dataset/training/'
train_data_filename = data_dir + 'images/'
train_labels_filename = data_dir + 'groundtruth/' 

# Extract it into numpy arrays.
train_data = extract_data(train_data_filename, TRAINING_SIZE)
train_labels = extract_labels(train_labels_filename, TRAINING_SIZE)

Loading 100 images
[[0.19215687 0.2509804  0.15294118]
 [0.21568628 0.27058825 0.1764706 ]
 [0.1764706  0.23921569 0.14901961]
 ...
 [0.11372549 0.10196079 0.08235294]
 [0.10196079 0.09411765 0.08235294]
 [0.00392157 0.         0.        ]]
Loading 100 images
satImage_054.png
Loading ../dataset/training/images/satImage_001.png
Loading ../dataset/training/images/satImage_002.png
Loading ../dataset/training/images/satImage_003.png
Loading ../dataset/training/images/satImage_004.png
Loading ../dataset/training/images/satImage_005.png
Loading ../dataset/training/images/satImage_006.png
Loading ../dataset/training/images/satImage_007.png
Loading ../dataset/training/images/satImage_008.png
Loading ../dataset/training/images/satImage_009.png
Loading ../dataset/training/images/satImage_010.png


NameError: name 'IMG_PATCH_SIZE' is not defined

In [3]:
# Choose model
model = BasicModel()

In [4]:
# Train
model.train(train_data, train_labels)

Number of data points per class: c0 = 4422 c1 = 1828
Balancing training data...
3656
(6250, 16, 16, 3)
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Number of data points per class: c0 = 1828 c1 = 1828
Epoch 1/1
6250/6250 [==============================] - 2s 299us/step - loss: 0.6323 - acc: 0.7024


In [9]:
# Save weights

In [10]:
# Predict Test Set

In [11]:
# Create submission