In [1]:
from constants import *
from basic_model import BasicModel
from vgg_model import VGGModel
from preprocessing_helper import *
from postprocessing_helper import *

import os
import sys

Using TensorFlow backend.


In [2]:
# Set Train data Directory
data_dir = '../dataset/training/'

In [3]:
# Option 1: Load entire images

image_dir = data_dir + "images/"
files = os.listdir(image_dir)
n = len(files)
print("Loading " + str(n) + " images")
imgs = [load_image(image_dir + files[i]) for i in range(n)]
print(imgs[0][2])

gt_dir = data_dir + "groundtruth/"
print("Loading " + str(n) + " images")
gt_imgs = [load_image(gt_dir + files[i]) for i in range(n)]
print(files[0])


Loading 100 images
[[0.19215687 0.2509804  0.15294118]
 [0.21568628 0.27058825 0.1764706 ]
 [0.1764706  0.23921569 0.14901961]
 ...
 [0.11372549 0.10196079 0.08235294]
 [0.10196079 0.09411765 0.08235294]
 [0.00392157 0.         0.        ]]
Loading 100 images
satImage_054.png


In [4]:
# Choose model
model = VGGModel()
# model = BasicModel()
# model = CNNModel()
# model = TeslaModelS()

In [5]:
# Option 2: Model loads files itself
model.load_data(image_dir, gt_dir, constants.TRAINING_SIZE)


Loading ../dataset/training/images/satImage_001.png
Loading ../dataset/training/images/satImage_002.png
Loading ../dataset/training/images/satImage_003.png
Loading ../dataset/training/images/satImage_004.png
Loading ../dataset/training/images/satImage_005.png
Loading ../dataset/training/images/satImage_006.png
Loading ../dataset/training/images/satImage_007.png
Loading ../dataset/training/images/satImage_008.png
Loading ../dataset/training/images/satImage_009.png
Loading ../dataset/training/images/satImage_010.png
Loading ../dataset/training/images/satImage_011.png
Loading ../dataset/training/images/satImage_012.png
Loading ../dataset/training/images/satImage_013.png
Loading ../dataset/training/images/satImage_014.png
Loading ../dataset/training/images/satImage_015.png
Loading ../dataset/training/images/satImage_016.png
Loading ../dataset/training/images/satImage_017.png
Loading ../dataset/training/images/satImage_018.png
Loading ../dataset/training/images/satImage_019.png
Loading ../d

In [6]:
# Train model
model.train(epochs=1, validation_split=0.1)

Epoch 1/1
1758/1757 [==============================] - 139s 79ms/step - loss: 0.6770 - acc: 0.7586 - val_loss: 0.4306 - val_acc: 0.8046


In [7]:
# Get F1 score
model.f1_score()

F1 score = 0.41884816753926696


In [8]:
# Create Training set images
# Set directory to save images
prediction_training_dir = "predictions_training/"
model.generate_images(prediction_training_dir, image_dir)

/home/ubuntu/road-segmentation/src/postprocessing_helper.py:115: RuntimeWarning: invalid value encountered in true_divide
  rimg = (rimg / numpy.max(rimg) * constants.PIXEL_DEPTH).round().astype(numpy.uint8)


In [9]:
# Predict Test Set -> Create submission and save Images
model.generate_submission()

In [10]:
# Save model
model.save()

Saved model to disk
